approvedGitRepositories:
  - '**'

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  midnight-ntwrk:
    npmMinimalAgeGate: 0
    npmPublishRegistry: 'https://npm.pkg.github.com/'
    npmRegistryServer: 'https://registry.npmjs.org/'
