compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  midnight-ntwrk:
    npmPublishRegistry: 'https://registry.npmjs.org/'
    npmRegistryServer: 'https://registry.npmjs.org/'
