name: License Header Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  license-header:
    name: Check License Headers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1

      - name: Check License Headers
        uses: apache/skywalking-eyes/header@a196742f472feaffafea537ce5a2a4c3c53a8de4 # main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
